name: plugin_nginx
on:
  pull_request:
    paths:
      - ".github/workflows/plugin_nginx.yml"
      - "plugins/nginx.yaml"
  push:
    branches:
      - master
jobs:
  plugin_nginx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Test Environment
      run: |
        mkdir stanza
        mkdir stanza/input
        mkdir stanza/output
        mkdir stanza/expect

        cat << EOF > stanza/input/access.log
        10.33.104.40 - - [11/Jan/2021:11:25:01 -0500] "GET / HTTP/1.1" 200 612 "-" "curl/7.58.0"
        10.33.104.40 - - [11/Jan/2021:11:25:01 -0500] "GET /help HTTP/1.1" 404 178 "-" "curl/7.58.0"
        10.33.104.40 - - [11/Jan/2021:11:25:01 -0500] "GET /about-us HTTP/1.1" 404 178 "-" "curl/7.58.0"
        EOF

        cat << EOF > stanza/input/error.log
        2021/02/25 16:51:01 [emerg] 18747#18747: duplicate "log_format" name "combined" in /root/nginx.conf.bad:43
        EOF

        cat << EOF > stanza/expect/expect.json
        {"timestamp":"2021-01-11T11:25:01-05:00","severity":30,"severity_text":"200","labels":{"file_name":"access.log","log_type":"nginx.access","plugin_id":"nginx"},"record":{"body_bytes_sent":"612","http_referer":"-","http_user_agent":"curl/7.58.0","method":"GET","path":"/","protocol":"HTTP","protocol_version":"1.1","remote_addr":"10.33.104.40","remote_user":"-","status":"200"}}
        {"timestamp":"2021-01-11T11:25:01-05:00","severity":50,"severity_text":"404","labels":{"file_name":"access.log","log_type":"nginx.access","plugin_id":"nginx"},"record":{"body_bytes_sent":"178","http_referer":"-","http_user_agent":"curl/7.58.0","method":"GET","path":"/help","protocol":"HTTP","protocol_version":"1.1","remote_addr":"10.33.104.40","remote_user":"-","status":"404"}}
        {"timestamp":"2021-01-11T11:25:01-05:00","severity":50,"severity_text":"404","labels":{"file_name":"access.log","log_type":"nginx.access","plugin_id":"nginx"},"record":{"body_bytes_sent":"178","http_referer":"-","http_user_agent":"curl/7.58.0","method":"GET","path":"/about-us","protocol":"HTTP","protocol_version":"1.1","remote_addr":"10.33.104.40","remote_user":"-","status":"404"}}
        EOF

        cat << EOF > stanza/config.yaml 
        pipeline:
        - type: nginx
          access_log_path: /ci/input/access.log
          error_log_path: /ci/input/error.log
          container_name: '*'
          enable_access_log: true
          enable_error_log: true
          log_format: default
          pod_name: '*'
          source: file
          start_at: beginning
        - type: file_output
          path: /ci/output/out
        EOF

    - name: Run Stanza
      run: |
        docker run -d \
          --entrypoint /stanza_home/stanza \
          -v $(pwd)/stanza:/ci \
          observiq/stanza:1.2.7 \
          --config /ci/config.yaml

    - name: Check output
      run: |
        if sudo diff stanza/expect/expect.json stanza/output/out; then
          echo "pass"
        else
          echo "fail"
          exit 1
        fi