name: plugin_kubernetes_container
on:
  pull_request:
    paths:
      - ".github/workflows/plugin_kubernetes_container.yml"
      - "plugins/kubernetes_container.yaml"
  push:
    branches:
      - master
jobs:
  default_format:
    runs-on: ubuntu-latest
    steps:
    - name: Clone stanza-plugins
      uses: actions/checkout@v2

    - name: Clone Log Library
      uses: actions/checkout@v2
      with:
        repository: 'observIQ/log-library'
        path: log-library
        token: ${{ secrets.LOG_LIBRARY_ACCESS_TOKEN }}
        ref: otel

    - name: Install Minikube
      run: |
        curl -s -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    # Start Minikube with --driver=none to run a k8s cluster within the actions
    # environment. This allows us to share configs, logs, and output with the container
    - name: Start Minikube
      run: |
        minikube start \
          --driver=none \
          --kubernetes-version=v1.20.0

    - name: Create Output Directory
      run: mkdir output

    - name: Create Offset Database Directory
      run: mkdir -p storage

    - name: Install Collector
      run: |
        mkdir -p collector
        curl -s -o collector/collector https://storage.googleapis.com/observiq-cloud/observiq-collector/0.0.10/collector_linux_amd64
        chmod +x collector/collector

    # This plugin requires /var/log/containers
    - name: Run Agent
      run: |
        docker run -d \
          --name agent \
          -v $(pwd)/collector:/collector \
          -v $(pwd)/log-library/cases/kubernetes_container/default:/input \
          -v $(pwd)/log-library/cases/kubernetes_container/default/logs:/var/log/containers \
          -v $(pwd)/output:/output \
          -v $(pwd)/plugins:/plugins \
          -v $(pwd)/storage:/storage \
          --entrypoint sh \
          ubuntu:20.04 \
          -c '/collector/collector --config /input/config/collector.yaml'
        
        sleep 1 && docker logs agent

    - name: Pause
      run: sleep 10

    - name: Stop Stanza
      run: docker kill agent

    - name: Dump Stanza Logs
      run: docker logs agent

    - name: Get Output
      run: |
        sudo cat output/out

    - name: Get Expected Output
      run: |
        sudo cp log-library/cases/kubernetes_container/default/expect/expect.json output/expect
        sudo cat output/expect

    - name: Install Json Parser 'jtool'
      run: |
        wget https://github.com/jsirianni/jtool/releases/download/v0.0.6/jtool-linux-amd64
        chmod +x jtool-linux-amd64

    - name: Check output
      run: |
        if sudo ./jtool-linux-amd64 --actual-file output/out --expect-file output/expect; then
          echo "pass"
        else
          echo "fail"
          exit 1
        fi