name: plugin_nginx
on:
  pull_request:
    paths:
      - ".github/workflows/plugin_nginx.yml"
      - "plugins/nginx.yaml"
  push:
    branches:
      - master
jobs:
  plugin_nginx:
    runs-on: ubuntu-latest
    steps:
    - name: Clone stanza-plugins
      uses: actions/checkout@v2

    - name: Clone Log Library
      uses: actions/checkout@v2
      with:
        repository: 'observIQ/log-library.git'
        path: log-library

    - name: Run Stanza
      run: |
        docker run -d \
          --name stanza \
          --entrypoint /stanza_home/stanza \
          -v $(pwd)/log-library/cases/nginx/default:/input \
          -v $(pwd)/output:/output \
          observiq/stanza:1.2.7 \
          --config /input/config/config.yaml

    - name: Pause 3 seconds
      run: sleep 3

    - name: Stop Stanza
      run: docker kill stanza

    - name: Check output
      run: |
        if sudo diff stanza/expect/expect.json stanza/output/out; then
          echo "pass"
        else
          echo "fail"
          exit 1
        fi