name: plugin_nginx
on:
  pull_request:
    paths:
      - ".github/workflows/plugin_nginx.yml"
      - "plugins/nginx.yaml"
  push:
    branches:
      - master
jobs:
  default_format:
    runs-on: ubuntu-latest
    steps:
    - name: Clone stanza-plugins
      uses: actions/checkout@v2

    - name: Clone Log Library
      uses: actions/checkout@v2
      with:
        repository: 'observIQ/log-library'
        path: log-library
        token: ${{ secrets.LOG_LIBRARY_ACCESS_TOKEN }}

    - name: Create Output Directory
      run: mkdir output

    - name: Run Stanza
      run: |
        docker run -d \
          --name stanza \
          --entrypoint /stanza_home/stanza \
          -v $(pwd)/log-library/cases/nginx/default:/input \
          -v $(pwd)/output:/output \
          observiq/stanza:1.2.7 \
          --config /input/config/config.yaml

    - name: Pause
      run: sleep 10

    - name: Dump Stanza Logs
      run: docker logs stanza

    - name: Stop Stanza
      run: docker kill stanza

    - name: Pause
      run: sleep 2

    - name: Cat output
      run: cat output/out

    - name: Cat expect
      run: cat log-library/cases/nginx/observiq/expect/expect.json

    - name: Check output
      run: |
        if sudo diff output/out log-library/cases/nginx/observiq/expect/expect.json; then
          echo "pass"
        else
          echo "fail"
          exit 1
        fi

  observiq_format:
    runs-on: ubuntu-latest
    steps:
    - name: Clone stanza-plugins
      uses: actions/checkout@v2

    - name: Clone Log Library
      uses: actions/checkout@v2
      with:
        repository: 'observIQ/log-library'
        path: log-library
        token: ${{ secrets.LOG_LIBRARY_ACCESS_TOKEN }}

    - name: Create Output Directory
      run: mkdir output

    - name: Run Stanza
      run: |
        docker run -d \
          --name stanza \
          --entrypoint /stanza_home/stanza \
          -v $(pwd)/log-library/cases/nginx/observiq:/input \
          -v $(pwd)/output:/output \
          observiq/stanza:1.2.7 \
          --config /input/config/config.yaml

    - name: Pause
      run: sleep 10

    - name: Stop Stanza
      run: docker kill stanza

    - name: Pause
      run: sleep 2

    - name: Cat output
      run: cat output/out

    - name: Cat expect
      run: cat log-library/cases/nginx/observiq/expect/expect.json

    - name: Dump Stanza Logs
      run: docker logs stanza

    - name: Check output
      run: |
        if sudo diff output/out log-library/cases/nginx/observiq/expect/expect.json; then
          echo "pass"
        else
          echo "fail"
          exit 1
        fi